import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Button, Col, Container, Form, Row } from 'react-bootstrap';
import { getPublicCardTypes } from '../../api/public.js';
import { guiAnhTuXa } from '../../api/intake.js';
import PublicFooter from '../../components/layout/PublicFooter.jsx';
import PublicTopbar from '../../components/layout/PublicTopbar.jsx';

const pickupSlots = ['08:00 - 09:00', '09:00 - 10:00', '10:00 - 11:00', '14:00 - 15:00', '15:00 - 16:00', '16:00 - 17:00'];
export default function RemoteUploadPage() {
  const [cards, setCards] = useState([]); const [files, setFiles] = useState([]); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ ho_ten: '', so_dien_thoai: '', email: '', loai_the_id: '', so_luong: 4, hinh_thuc_giao: 'lay_file_truc_tuyen', ngay_hen_lay: '', khung_gio_lay: '', ghi_chu: '' });
  useEffect(() => { getPublicCardTypes().then((d) => setCards(d.card_types || [])).catch((e) => setError(e.message)); }, []);
  const update = (e) => setForm((old) => ({ ...old, [e.target.name]: e.target.value }));
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { setResult(await guiAnhTuXa({ fields: form, files })); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <div className="public-page"><Container><PublicTopbar /><Row className="justify-content-center"><Col xl={8}><section className="app-panel public-panel"><div className="public-heading"><span className="lookup-badge">Gửi ảnh từ xa</span><h1>Gửi ảnh để tiệm xử lý</h1><p>Đơn được tạo ngay sau khi bạn gửi ảnh. File trực tuyến chỉ tải được khi đơn đã giao và thanh toán đủ.</p></div>
    {result && <div className="alert alert-success">Đã tạo đơn <strong>{result.order?.ma_don}</strong>. Xác nhận đã gửi về email của bạn.</div>}{error && <div className="alert alert-danger">{error}</div>}
    <form onSubmit={submit} className="row g-3"><div className="col-md-6"><label>Họ tên</label><input required name="ho_ten" className="form-control" value={form.ho_ten} onChange={update}/></div><div className="col-md-6"><label>Số điện thoại</label><input required name="so_dien_thoai" className="form-control" value={form.so_dien_thoai} onChange={update}/></div><div className="col-12"><label>Email</label><input required type="email" name="email" className="form-control" value={form.email} onChange={update}/></div><div className="col-md-6"><label>Loại thẻ</label><select required name="loai_the_id" className="form-select" value={form.loai_the_id} onChange={update}><option value="">Chọn loại thẻ</option>{cards.map((card) => <option value={card.id} key={card.id}>{card.ten}</option>)}</select></div><div className="col-md-6"><label>Số lượng</label><input required min="4" type="number" name="so_luong" className="form-control" value={form.so_luong} onChange={update}/></div><div className="col-12"><label>Ảnh cần xử lý</label><input required multiple accept="image/jpeg,image/png,image/webp" type="file" className="form-control" onChange={(e) => setFiles(Array.from(e.target.files || []))}/><small>{files.length ? `${files.length} ảnh đã chọn` : 'JPEG, PNG hoặc WEBP'}</small></div><div className="col-12"><label>Hình thức giao</label><select name="hinh_thuc_giao" className="form-select" value={form.hinh_thuc_giao} onChange={update}><option value="lay_file_truc_tuyen">Chỉ lấy file trực tuyến</option><option value="hen_lay_hinh">Hẹn lấy hình in</option></select></div>{form.hinh_thuc_giao === 'hen_lay_hinh' && <><div className="col-md-6"><label>Ngày lấy hình</label><input required type="date" name="ngay_hen_lay" className="form-control" value={form.ngay_hen_lay} onChange={update}/></div><div className="col-md-6"><label>Khung giờ lấy</label><select required name="khung_gio_lay" className="form-select" value={form.khung_gio_lay} onChange={update}><option value="">Chọn giờ</option>{pickupSlots.map((s) => <option key={s}>{s}</option>)}</select></div></>}<div className="col-12"><button disabled={busy} className="btn btn-primary">{busy ? 'Đang gửi…' : 'Tạo đơn và gửi ảnh'}</button> <Link className="btn btn-outline-secondary" to="/dat-lich">Đặt lịch chụp</Link></div></form>
  </section></Col></Row></Container><PublicFooter /></div>;
}
